services:

  nginx:
    networks:
      - default
      - dokploy-network
    ports: []   # отключаем 8080:80

  api:
    networks:
      - default
      - dokploy-network

  web:
    networks:
      - default
      - dokploy-network

networks:

  dokploy-network:
    external: true
