services:
  nginx:
    profiles: ["disabled"]

  certbot:
    profiles: ["disabled"]

  api:
    networks:
      - default
      - dokploy-network

  web:
    networks:
      - default
      - dokploy-network

networks:
  dokploy-network:
    external: true
